#!/usr/bin/env bash
#
# Publish ./dist-pages to the gh-pages branch.
#
#   npm run build:pages && npm run deploy:pages
#
# Uses a detached git worktree rather than checking out gh-pages in place, so
# your working tree, current branch and uncommitted work are never touched.
# The published branch is replaced wholesale each time — it is a build output,
# not a history worth preserving.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="$ROOT/dist-pages"
WORKTREE="$(mktemp -d)"
BRANCH="gh-pages"

if [ ! -f "$DIST/index.html" ]; then
  echo "error: $DIST/index.html missing — run 'npm run build:pages' first." >&2
  exit 1
fi

cleanup() {
  git -C "$ROOT" worktree remove --force "$WORKTREE" 2>/dev/null || true
  rm -rf "$WORKTREE"
}
trap cleanup EXIT

echo "Fetching $BRANCH…"
git -C "$ROOT" fetch origin "$BRANCH" --quiet || true

if git -C "$ROOT" rev-parse --verify --quiet "origin/$BRANCH" >/dev/null; then
  git -C "$ROOT" worktree add --detach "$WORKTREE" "origin/$BRANCH" --quiet
  git -C "$WORKTREE" checkout -B "$BRANCH" --quiet
else
  git -C "$ROOT" worktree add --detach "$WORKTREE" --quiet
  git -C "$WORKTREE" checkout --orphan "$BRANCH" --quiet
fi

# Wipe tracked content, keeping .git itself. The snapshot is authoritative:
# stale object/passport JSON from a previous catalog must not survive.
find "$WORKTREE" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -R "$DIST"/. "$WORKTREE"/

cd "$WORKTREE"
git add -A
if git diff --cached --quiet; then
  echo "No changes to publish."
  exit 0
fi

COUNT=$(ls "$DIST/api/object" | wc -l | tr -d ' ')
git commit --quiet -m "Static Pages snapshot: ${COUNT} objects with stolen-art register checks

Regenerated by scripts/build-pages.ts. Includes the INTERPOL / FBI NSAF /
Carabinieri TPC / Lost Art / Getty / ICOM / Wikidata register layer and the
expanded object catalog.

Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>"
git push --force origin "$BRANCH" --quiet

echo "Published $COUNT objects to $BRANCH → https://ethical-tech-colab.github.io/arts-provenance-agent/"
